### ISSUE TITLE
strange bibl entries

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-spa#1]
Three titles ( SPA4008, SPA4014, SPA4017) have a mysterious and probably redundant
`<bibl type="digitalSource">Abbyy Recognition Server, <date when="2017">2017</date>.</bibl>`
in addition to a bibl referencing the CoNSSA. What does this mean?

**Comment by bncolorado** [comment]
Nothing. It has been deleted. Thanks...
